# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f387cda493b468ee4ff539a4321fcce4184878999adaa0c9434fe647666c8e46e0ef51d45a449cf9fe30529ad017770b1528427afd6def645bfd35a5a25e9d3

test:
  secret_key_base: c5355d00cd686404503397f8050a8cd59025f7b9a8ef306966f2d0943f3675a05cd9f998e046ab4bc44ee5927590a4af2a5d1a0f6d3301132f78870bc932d5fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
